spring:
  datasource:
    url: jdbc:mysql://localhost:3306/parc
    #driverClassName: com.mysql.cj.jdbc.Driver
    password: root
    username: root
  jpa:
    database: mysql
    open-in-view: true
    show-sql: true
  hibernate:
  #配置指明在程序启动的时候要删除并且创建实体类对应的表
    ddl-auto: create

server:
  port: 9911
